# Generated by Django 2.2.12 on 2020-04-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('featured', 'Featured'), ('side_story', 'Side Story'), ('trending', 'Trending')], max_length=50),
        ),
    ]
