# Generated by Django 2.2.12 on 2020-04-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('featured', 'Featured'), ('side_story', 'Side Story'), ('trending', 'Trending'), ('bin', 'bin')], max_length=50),
        ),
    ]
